### PR TITLE
Nexus Options fixed

### PR DESCRIPTION
**Pull request by ExtendedEvil**
Fixed Kazumis Nuke displaying a cdi marine text and reorganized

### CODE REVIEW

**Comment by ExtendedEvil** [comment]
I added missing variables to the beheadedkamikaze and changed the explosion to something different, because "LegZombieSuicideBomb" looks bad and is over the top. (See Screenshot). Pretty much everything that uses that explosion looks bad. Its way too big and too long. CF 4.3 is so broken at some points, people would be honestly better off playing 4.1 for now, for example, Legendary Redeemer doesn't even explode (tested on 4.3 with v4 patch and inexus) and Enraged Legendary Tormentor doesn't have any sounds. I just found out about them, when looking for a explosion actor that isn't "LegZombieSuicideBomb".

gzdoom_lhixrq4yAw

**Comment by MrSatan6666** [comment]
LegendaryRedeemer does explode I just tested it.  Which sound is EnragedLegendaryTormentor missing?  CF 4.1 is way more broken than 4.3. Lots of actors that reek havoc on servers, lots of monster infighting that shouldn't, monsters/weapons that do way too much damage, infinite recursion.  Add Nexus to that and the brokenness increases 10 fold.
I have a feeling you are from a certain community here to cause trouble.

**Comment by ExtendedEvil** [comment]
> LegendaryRedeemer does explode I just tested it. Which sound is EnragedLegendaryTormentor missing? CF 4.1 is way more broken than 4.3. Lots of actors that reek havoc on servers, lots of monster infighting that shouldn't, monsters/weapons that do way too much damage, infinite recursion. Add Nexus to that and the brokenness increases 10 fold. I have a feeling you are from a certain community here to cause trouble.

I'm not here to cause trouble, but it seems like the drama is still a thing, sadly. If I were to cause trouble, I wouldn't update the link in the readme to the 4.3 server, so new players could potentially join. Anyway I'll add a video of the LegRedeemer and Tormentor both tested on v4.3 and the patch, freshly downloaded from TSPG, using GZDoom.


https://github.com/TonynUBares/improved-nexus-v0.41d/assets/132709897/2c9b332b-d698-4fb3-b4cd-55041fe73d7e

**Comment by MrSatan6666** [comment]
Oh when they die.  It's better to report CF bugs on the Discord server.  I really don't pay much attention to this GitHub.

**Pull request merged**
